package lib

const (
	// Plugin and REST/websocket API things
	DONT_RESTART_EXIT_CODE        = 100
	UNLOAD_PLUGIN_KILL_DELAY      = 3000
	ACTION_STATUS                 = "tatus"
	ADAPTER_ADDED                 = "adapterAdded"
	ADAPTER_UNLOADED              = "adapterUnloaded"
	ADD_ADAPTER                   = "addAdapter"
	ADD_EVENT_SUBSCRIPTION        = "addEventSubscription"
	ADD_MOCK_DEVICE               = "addMockDevice"
	CANCEL_PAIRING                = "cancelPairing"
	CANCEL_REMOVE_THING           = "cancelRemoveThing"
	CLEAR_MOCK_ADAPTER_STATE      = "clearMockAdapterState"
	CONNECTED                     = "connected"
	DEBUG_CMD                     = "debugCmd"
	EVENT                         = "event"
	ERROR                         = "error"
	HANDLE_DEVICE_ADDED           = "handleDeviceAdded"
	HANDLE_DEVICE_REMOVED         = "handleDeviceRemoved"
	MOCK_ADAPTER_STATE_CLEARED    = "mockAdapterStateCleared"
	MOCK_DEVICE_ADDED_REMOVED     = "mockDeviceAddedRemoved"
	MOCK_DEVICE_ADD_REMOVE_FAILED = "mockDeviceAddRemoveFailed"
	PAIRING_TIMEOUT               = "pairingTimeout"
	PAIR_MOCK_DEVICE              = "pairMockDevice"
	PLUGIN_UNLOADED               = "pluginUnloaded"
	PLUGIN_ERROR                  = "pluginError"
	PROPERTY_CHANGED              = "propertyChanged"
	PROPERTY_STATUS               = "propertyStatus"
	REGISTER_PLUGIN               = "registerPlugin"
	REGISTER_PLUGIN_REPLY         = "registerPluginReply"
	REMOVE_ACTION                 = "removeAction"
	REMOVE_ACTION_REJECTED        = "removeActionRejected"
	REMOVE_ACTION_RESOLVED        = "removeActionResolved"
	REMOVE_THING                  = "removeThing"
	REQUEST_ACTION                = "requestAction"
	REQUEST_ACTION_REJECTED       = "requestActionRejected"
	REQUEST_ACTION_RESOLVED       = "requestActionResolved"
	SET_PIN                       = "setPin"
	SET_PIN_REJECTED              = "setPinRejected"
	SET_PIN_RESOLVED              = "setPinResolved"
	SET_PROPERTY                  = "setProperty"
	START_PAIRING                 = "startPairing"
	THING_ADDED                   = "thingAdded"
	THING_REMOVED                 = "thingRemoved"
	UNLOAD_ADAPTER                = "unloadAdapter"
	UNLOAD_PLUGIN                 = "unloadPlugin"
	UNPAIR_MOCK_DEVICE            = "unpairMockDevice"

	// Thing types
	THING_TYPE_ON_OFF_SWITCH        = "onOffSwitch"
	THING_TYPE_MULTI_LEVEL_SWITCH   = "multiLevelSwitch"
	THING_TYPE_BINARY_SENSOR        = "binarySensor"
	THING_TYPE_MULTI_LEVEL_SENSOR   = "multiLevelSensor"
	THING_TYPE_SMART_PLUG           = "smartPlug"
	THING_TYPE_ON_OFF_LIGHT         = "onOffLight"
	THING_TYPE_DIMMABLE_LIGHT       = "dimmableLight"
	THING_TYPE_ON_OFF_COLOR_LIGHT   = "onOffColorLight"
	THING_TYPE_DIMMABLE_COLOR_LIGHT = "dimmableColorLight"
)
